name: test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: test-${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        include:
          - platform: ubuntu-latest
            install: |
              sudo apt-get update
              sudo apt-get install -y libpng-dev gcc-aarch64-linux-gnu

          - platform: ubuntu-24.04-arm
            install: |
              sudo apt-get update
              sudo apt-get install -y libpng-dev gcc-x86-64-linux-gnu

          - platform: windows-latest
            install: |
              vcpkg install libpng:x64-windows
              echo "C:\vcpkg\installed\x64-windows\bin" >> $env:GITHUB_PATH

          - platform: windows-11-arm
            install: |
              vcpkg install libpng:arm64-windows
              echo "C:\vcpkg\installed\arm64-windows\bin" >> $env:GITHUB_PATH

          - platform: macos-latest
            install: ""

          - platform: macos-15-intel
            install: ""
    steps:
      - uses: actions/checkout@v4

      - if: matrix.install != ''
        run: ${{ matrix.install }}

      - run: |
          cmake -S . -B build
          cmake --build build
          ctest --test-dir build --verbose -C Debug
